name: 'ReView Builder'
description: 'ReView Builder for Github Actions'
author: Chatyusha
branding:
  icon: book
  color: red

inputs:
  path:
    description: 'the path of document root'
    required: true
    default: "./"
  type:
    description: 'the type of document'
    required: true
    default: 'pdf'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.type }}
