name: 'RiView Builder'
description: 'ReView Builder for Github Actions'
icon: book
color: red

inputs:
  branch:
    description: 'target branch name'
    required: true
    default: 'master'
  path:
    description: 'the path of document root'
    required: true
    default: "./"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
