name: 'RiView Builder'
description: 'ReView Builder for Github Actions'

inputs:
  branch:
    description: 'target branch name'
    required: true
    default: 'master'
  path:
    description: 'the path of document root'
    required: true
    default: "./"

runs:
  using: 'composite'
  steps:
    - run: gem install review
    - run: gem install bundler
    - run: ./entrypoint.sh ${{ inputs.branch }} ${{ inputs.path }}
