name: 'RiView Builder'
description: 'ReView Builder for Github Actions'

inputs:
  branch:
  path:
    description: 'the path of document root'
    required: false
    default: "sample"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
