on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Review Article
        uses: ./
        with:
          path: sample
          outdir: "artifacts"
          type: "pdf,web"

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: books
          path: "sample/artifacts"
          
  usetest:
    runs-on: ubuntu-latest
    name: test job2
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Review Article
        uses: Chatyusha/review-action@2.0
        with:
          path: sample
          outdir: "artifacts"
          type: "pdf,web"
