on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Review Build Job
        uses: ./ # Uses an action in the root directory
      - name: docker logs save 2
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: ./sample/book.pdf 
